### ISSUE TITLE
Missing colourtag.css link

### ISSUE THREAD

**Issue by elixirgraphics** [realmacsoftware/RWThemeKit#2]
The ```<head></head>``` of the index.html file does not contain a link to the colourtag.css file.

It should include something like this, otherwise color pickers will not function.
```html
<!-- RapidWeaver Color Picker Stylesheet -->
<link rel="stylesheet" type="text/css" media="screen" href="%pathto(colourtag.css)%" />  
```

**Comment by nikf** [comment]
Thanks for fixing in https://github.com/realmacsoftware/RWThemeKit/commit/46af645b328ba9acfc74d17ff1337562f39c7125#diff-28b668b62ce5c37e7d34ae834191ffdf
